// <auto-generated />
namespace DvdLibrary.Data.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class notnotes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(notnotes));
        
        string IMigrationMetadata.Id
        {
            get { return "201710230137193_notnotes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
